package com.zzolta.android.glutenfreerecipes.utils;

/**
 * Created by Zolta.Szekely on 2015-02-28.
 */
public final class OfflineRecipeDetailResult {
    public static final String pizzaFriesRecipeDetailResult = "{\n" +
                                                              "   \"yield\":null,\n" +
                                                              "   \"nutritionEstimates\":[\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FAT_KCAL\",\n" +
                                                              "         \"description\":null,\n" +
                                                              "         \"value\":50.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"fea252f8-9888-4365-b005-e2c63ed3a776\",\n" +
                                                              "            \"name\":\"calorie\",\n" +
                                                              "            \"abbreviation\":\"kcal\",\n" +
                                                              "            \"plural\":\"calories\",\n" +
                                                              "            \"pluralAbbreviation\":\"kcal\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"K\",\n" +
                                                              "         \"description\":\"Potassium, K\",\n" +
                                                              "         \"value\":0.25,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FLD\",\n" +
                                                              "         \"description\":\"Fluoride, F\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"PHYSTR\",\n" +
                                                              "         \"description\":\"Phytosterols\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"VAL_G\",\n" +
                                                              "         \"description\":\"Valine\",\n" +
                                                              "         \"value\":0.18,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"F18D1C\",\n" +
                                                              "         \"description\":\"18:1 c\",\n" +
                                                              "         \"value\":1.05,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"F18D2CN6\",\n" +
                                                              "         \"description\":\"18:2 n-6 c,c\",\n" +
                                                              "         \"value\":0.23,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FASAT\",\n" +
                                                              "         \"description\":\"Fatty acids, total saturated\",\n" +
                                                              "         \"value\":2.51,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FOLDFE\",\n" +
                                                              "         \"description\":\"Folate, DFE\",\n" +
                                                              "         \"value\":1.12,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"4d783ee4-aa07-4958-84bf-3f4b528049dc\",\n" +
                                                              "            \"name\":\"mcg_DFE\",\n" +
                                                              "            \"abbreviation\":\"mcg_DFE\",\n" +
                                                              "            \"plural\":\"mcg_DFE\",\n" +
                                                              "            \"pluralAbbreviation\":\"mcg_DFE\",\n" +
                                                              "            \"decimal\":false\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"MN\",\n" +
                                                              "         \"description\":\"Manganese, Mn\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"F12D0\",\n" +
                                                              "         \"description\":\"12:0\",\n" +
                                                              "         \"value\":0.11,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"GLUS\",\n" +
                                                              "         \"description\":\"Glucose (dextrose)\",\n" +
                                                              "         \"value\":0.11,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"ARG_G\",\n" +
                                                              "         \"description\":\"Arginine\",\n" +
                                                              "         \"value\":0.18,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"F16D1\",\n" +
                                                              "         \"description\":\"16:1 undifferentiated\",\n" +
                                                              "         \"value\":0.18,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"ALA_G\",\n" +
                                                              "         \"description\":\"Alanine\",\n" +
                                                              "         \"value\":0.18,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"F18D1T\",\n" +
                                                              "         \"description\":\"18:1 t\",\n" +
                                                              "         \"value\":0.08,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FOLFD\",\n" +
                                                              "         \"description\":\"Folate, food\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"TYR_G\",\n" +
                                                              "         \"description\":\"Tyrosine\",\n" +
                                                              "         \"value\":0.18,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FE\",\n" +
                                                              "         \"description\":\"Iron, Fe\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"ENERC_KJ\",\n" +
                                                              "         \"description\":\"Energy\",\n" +
                                                              "         \"value\":430.57,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"fea252f8-9888-4365-b005-e2c63ed3a776\",\n" +
                                                              "            \"name\":\"calorie\",\n" +
                                                              "            \"abbreviation\":\"kcal\",\n" +
                                                              "            \"plural\":\"calories\",\n" +
                                                              "            \"pluralAbbreviation\":\"kcal\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"HISTN_G\",\n" +
                                                              "         \"description\":\"Histidine\",\n" +
                                                              "         \"value\":0.18,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"F4D0\",\n" +
                                                              "         \"description\":\"4:0\",\n" +
                                                              "         \"value\":0.11,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"ASP_G\",\n" +
                                                              "         \"description\":\"Aspartic acid\",\n" +
                                                              "         \"value\":0.36,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"WATER\",\n" +
                                                              "         \"description\":\"Water\",\n" +
                                                              "         \"value\":62.45,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"RETOL\",\n" +
                                                              "         \"description\":\"Retinol\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"SUGAR\",\n" +
                                                              "         \"description\":\"Sugars, total\",\n" +
                                                              "         \"value\":1.37,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FAMS\",\n" +
                                                              "         \"description\":\"Fatty acids, total monounsaturated\",\n" +
                                                              "         \"value\":2.02,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"GLY_G\",\n" +
                                                              "         \"description\":\"Glycine\",\n" +
                                                              "         \"value\":0.18,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"ASH\",\n" +
                                                              "         \"description\":\"Ash\",\n" +
                                                              "         \"value\":1.32,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"SE\",\n" +
                                                              "         \"description\":\"Selenium, Se\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FIBTG\",\n" +
                                                              "         \"description\":\"Fiber, total dietary\",\n" +
                                                              "         \"value\":1.26,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"PROCNT\",\n" +
                                                              "         \"description\":\"Protein\",\n" +
                                                              "         \"value\":5.32,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"PHE_G\",\n" +
                                                              "         \"description\":\"Phenylalanine\",\n" +
                                                              "         \"value\":0.18,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"CHOCDF\",\n" +
                                                              "         \"description\":\"Carbohydrate, by difference\",\n" +
                                                              "         \"value\":5.88,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FOL\",\n" +
                                                              "         \"description\":\"Folate, total\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"VITK\",\n" +
                                                              "         \"description\":\"Vitamin K (phylloquinone)\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"F18D0\",\n" +
                                                              "         \"description\":\"18:0\",\n" +
                                                              "         \"value\":0.59,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"LEU_G\",\n" +
                                                              "         \"description\":\"Leucine\",\n" +
                                                              "         \"value\":0.36,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"CHOLE\",\n" +
                                                              "         \"description\":\"Cholesterol\",\n" +
                                                              "         \"value\":0.02,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"P\",\n" +
                                                              "         \"description\":\"Phosphorus, P\",\n" +
                                                              "         \"value\":0.08,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"PANTAC\",\n" +
                                                              "         \"description\":\"Pantothenic acid\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"CHOLN\",\n" +
                                                              "         \"description\":\"Choline, total\",\n" +
                                                              "         \"value\":0.01,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"F10D0\",\n" +
                                                              "         \"description\":\"10:0\",\n" +
                                                              "         \"value\":0.11,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"CA\",\n" +
                                                              "         \"description\":\"Calcium, Ca\",\n" +
                                                              "         \"value\":0.09,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"MG\",\n" +
                                                              "         \"description\":\"Magnesium, Mg\",\n" +
                                                              "         \"value\":0.02,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FAPU\",\n" +
                                                              "         \"description\":\"Fatty acids, total polyunsaturated\",\n" +
                                                              "         \"value\":0.33,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"F14D0\",\n" +
                                                              "         \"description\":\"14:0\",\n" +
                                                              "         \"value\":0.29,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"MET_G\",\n" +
                                                              "         \"description\":\"Methionine\",\n" +
                                                              "         \"value\":0.18,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FATRNM\",\n" +
                                                              "         \"description\":\"Fatty acids, total trans-monoenoic\",\n" +
                                                              "         \"value\":0.08,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"VITB12\",\n" +
                                                              "         \"description\":\"Vitamin B-12\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"VITA_RAE\",\n" +
                                                              "         \"description\":\"Vitamin A, RAE\",\n" +
                                                              "         \"value\":19.03,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"0fcf76b3-891a-403d-883f-58c8809ef151\",\n" +
                                                              "            \"name\":\"mcg_RAE\",\n" +
                                                              "            \"abbreviation\":\"mcg_RAE\",\n" +
                                                              "            \"plural\":\"mcg_RAE\",\n" +
                                                              "            \"pluralAbbreviation\":\"mcg_RAE\",\n" +
                                                              "            \"decimal\":false\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"NIA\",\n" +
                                                              "         \"description\":\"Niacin\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"GLU_G\",\n" +
                                                              "         \"description\":\"Glutamic acid\",\n" +
                                                              "         \"value\":0.65,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"F16D0\",\n" +
                                                              "         \"description\":\"16:0\",\n" +
                                                              "         \"value\":1.21,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"F18D1\",\n" +
                                                              "         \"description\":\"18:1 undifferentiated\",\n" +
                                                              "         \"value\":1.84,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"F18D2\",\n" +
                                                              "         \"description\":\"18:2 undifferentiated\",\n" +
                                                              "         \"value\":0.23,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"BETN\",\n" +
                                                              "         \"description\":\"Betaine\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"THR_G\",\n" +
                                                              "         \"description\":\"Threonine\",\n" +
                                                              "         \"value\":0.18,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"CARTB\",\n" +
                                                              "         \"description\":\"Carotene, beta\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"LYS_G\",\n" +
                                                              "         \"description\":\"Lysine\",\n" +
                                                              "         \"value\":0.26,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"SER_G\",\n" +
                                                              "         \"description\":\"Serine\",\n" +
                                                              "         \"value\":0.18,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"ILE_G\",\n" +
                                                              "         \"description\":\"Isoleucine\",\n" +
                                                              "         \"value\":0.18,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"VITA_IU\",\n" +
                                                              "         \"description\":\"Vitamin A, IU\",\n" +
                                                              "         \"value\":492.08,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"ed46fe0c-44fe-4c1f-b3a8-880f92e30930\",\n" +
                                                              "            \"name\":\"IU\",\n" +
                                                              "            \"abbreviation\":\"IU\",\n" +
                                                              "            \"plural\":\"IU\",\n" +
                                                              "            \"pluralAbbreviation\":\"IU\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FATRN\",\n" +
                                                              "         \"description\":\"Fatty acids, total trans\",\n" +
                                                              "         \"value\":0.15,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"ENERC_KCAL\",\n" +
                                                              "         \"description\":\"Energy\",\n" +
                                                              "         \"value\":102.96,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"fea252f8-9888-4365-b005-e2c63ed3a776\",\n" +
                                                              "            \"name\":\"calorie\",\n" +
                                                              "            \"abbreviation\":\"kcal\",\n" +
                                                              "            \"plural\":\"calories\",\n" +
                                                              "            \"pluralAbbreviation\":\"kcal\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"VITC\",\n" +
                                                              "         \"description\":\"Vitamin C, total ascorbic acid\",\n" +
                                                              "         \"value\":0.01,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"TRP_G\",\n" +
                                                              "         \"description\":\"Tryptophan\",\n" +
                                                              "         \"value\":0.11,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"FAT\",\n" +
                                                              "         \"description\":\"Total lipid (fat)\",\n" +
                                                              "         \"value\":6.27,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"PRO_G\",\n" +
                                                              "         \"description\":\"Proline\",\n" +
                                                              "         \"value\":0.29,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"VITD-\",\n" +
                                                              "         \"description\":\"Vitamin D\",\n" +
                                                              "         \"value\":2.38,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"ed46fe0c-44fe-4c1f-b3a8-880f92e30930\",\n" +
                                                              "            \"name\":\"IU\",\n" +
                                                              "            \"abbreviation\":\"IU\",\n" +
                                                              "            \"plural\":\"IU\",\n" +
                                                              "            \"pluralAbbreviation\":\"IU\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"ZN\",\n" +
                                                              "         \"description\":\"Zinc, Zn\",\n" +
                                                              "         \"value\":0.00,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      },\n" +
                                                              "      {\n" +
                                                              "         \"attribute\":\"NA\",\n" +
                                                              "         \"description\":\"Sodium, Na\",\n" +
                                                              "         \"value\":0.31,\n" +
                                                              "         \"unit\":{\n" +
                                                              "            \"id\":\"12485d26-6e69-102c-9a8a-0030485841f8\",\n" +
                                                              "            \"name\":\"gram\",\n" +
                                                              "            \"abbreviation\":\"g\",\n" +
                                                              "            \"plural\":\"grams\",\n" +
                                                              "            \"pluralAbbreviation\":\"grams\",\n" +
                                                              "            \"decimal\":true\n" +
                                                              "         }\n" +
                                                              "      }\n" +
                                                              "   ],\n" +
                                                              "   \"totalTime\":\"30 min\",\n" +
                                                              "   \"images\":[\n" +
                                                              "      {\n" +
                                                              "         \"imageUrlsBySize\":{\n" +
                                                              "            \"90\":\"http://lh6.ggpht.com/s8HKd3k2bvDs_uYdvnrzLgEu_avZx22M99gWroxFFewj1heEiSzwqRJQPn6bd4dMz0RC7LWdaGRTYqH-RakQ=s90-c\",\n" +
                                                              "            \"360\":\"http://lh6.ggpht.com/s8HKd3k2bvDs_uYdvnrzLgEu_avZx22M99gWroxFFewj1heEiSzwqRJQPn6bd4dMz0RC7LWdaGRTYqH-RakQ=s360-c\"\n" +
                                                              "         },\n" +
                                                              "         \"hostedSmallUrl\":\"http://lh6.ggpht.com/vvcsypBCsLiWsUghvYFvHPFFPfJecB7JUBfEtk9t9YRl-ZF-Igsearr5VBggpOXUqTk3-dIkTIOOH-7mmiTNLQ=s90\",\n" +
                                                              "         \"hostedMediumUrl\":\"http://lh6.ggpht.com/vvcsypBCsLiWsUghvYFvHPFFPfJecB7JUBfEtk9t9YRl-ZF-Igsearr5VBggpOXUqTk3-dIkTIOOH-7mmiTNLQ=s180\",\n" +
                                                              "         \"hostedLargeUrl\":\"http://lh6.ggpht.com/vvcsypBCsLiWsUghvYFvHPFFPfJecB7JUBfEtk9t9YRl-ZF-Igsearr5VBggpOXUqTk3-dIkTIOOH-7mmiTNLQ=s360\"\n" +
                                                              "      }\n" +
                                                              "   ],\n" +
                                                              "   \"name\":\"Pizza Fries\",\n" +
                                                              "   \"source\":{\n" +
                                                              "      \"sourceRecipeUrl\":\"http://www.whipitup4foodies.com/uncategorized/pizza-fries/\",\n" +
                                                              "      \"sourceSiteUrl\":\"whipitup4foodies.com\",\n" +
                                                              "      \"sourceDisplayName\":\"Whippin It Up 4 Foodies \"\n" +
                                                              "   },\n" +
                                                              "   \"id\":\"Pizza-Fries-753754\",\n" +
                                                              "   \"ingredientLines\":[\n" +
                                                              "      \"1   two pound bag frozen french fries\",\n" +
                                                              "      \"1   cup Pizza Sauce\",\n" +
                                                              "      \"1 1/2  cups shredded mozzarella cheese (about 6 ounces)\",\n" +
                                                              "      \"Diced pepperoni, optional\"\n" +
                                                              "   ],\n" +
                                                              "   \"attribution\":{\n" +
                                                              "      \"html\":\"<a href='http://www.yummly.com/recipe/Pizza-Fries-753754'>Pizza Fries recipe</a> information powered by <img alt='Yummly' src='http://static.yummly.com/api-logo.png'/>\",\n" +
                                                              "      \"url\":\"http://www.yummly.com/recipe/Pizza-Fries-753754\",\n" +
                                                              "      \"text\":\"Pizza Fries recipes: information powered by Yummly\",\n" +
                                                              "      \"logo\":\"http://static.yummly.com/api-logo.png\"\n" +
                                                              "   },\n" +
                                                              "   \"numberOfServings\":4,\n" +
                                                              "   \"totalTimeInSeconds\":1800,\n" +
                                                              "   \"attributes\":{\n" +
                                                              "      \"cuisine\":[\n" +
                                                              "         \"Kid-Friendly\"\n" +
                                                              "      ]\n" +
                                                              "   },\n" +
                                                              "   \"flavors\":{\n" +
                                                              "      \"Sweet\":0.1667,\n" +
                                                              "      \"Salty\":0.8333,\n" +
                                                              "      \"Meaty\":0.1667,\n" +
                                                              "      \"Sour\":0.5000,\n" +
                                                              "      \"Bitter\":0.6667,\n" +
                                                              "      \"Piquant\":0.0000\n" +
                                                              "   },\n" +
                                                              "   \"rating\":4\n" +
                                                              "}";

    private OfflineRecipeDetailResult() {
    }
}
